language: android
sudo: false

android:
  components:
    - android-28
    - tools
    - build-tools-28.0.1
    
os:
  - linux
  
jdk:
  - oraclejdk8
  
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck
  - chmod +x ./gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash)
