language: android
sudo: false

android:
  components:
    - android-28
    - android-24
    - tools
    - platform-tools
    - build-tools-28.0.0
    
os:
  - linux
  
jdk: 
  - oraclejdk8

script:
  - chmod +x gradlew
